Items for Overcoming Extreme Climatic Obstacles
Terasology/WildAnimals pull request #56
Opened 2020-06-24 11:36 UTC by ktksan

This PR is a support PR for : https://github.com/Terasology/ManualLabor/pull/30
NOTE; the png textures are temporary and are to be treated as placeholders for final artwork.

2020-06-25 15:58 UTC, jdrueckert commented
LGTM, the only thing I wondered: you created deer hide, but did you also adjust the deer to drop some? 🤔 Did I overlook that? If so, can you give me a quick pointer on where to look? 😅

2020-06-25 16:30 UTC, ktksan commented
Nope you didn't miss it, I just forgot to add the file(deer.prefab) in here 😅, added now.

2020-06-25 16:55 UTC, jdrueckert requested changes

2020-06-25 16:55 UTC, jdrueckert commented on assets/prefabs/animals/deer.prefab
> +    "itemDrops": ["WildAnimals:deerHide"]
Please don't overwrite the old item drop, I believe e.g. MR depends on deer dropping meat as a food source.
`DropGrammar` should allow you to
- either add multiple drops
- or (which I'd prefer) drop each of the two possible drops (meet, hide) with a certain probability

2020-06-30 09:36 UTC, ktksan commented on assets/prefabs/animals/deer.prefab
> +    "itemDrops": ["WildAnimals:deerHide"]
Yes I've added the two possible drops but both these drops will have their individual probability of drop which would be independent of each other, which means at any point of time, there can be either one of the two items, both items together, or even none at all.

2020-07-04 16:51 UTC, jdrueckert requested changes
Tip for item descriptions: if you have the item name, check that in an english-english dictionary (explains words using synonyms or descriptive phrases)

2020-07-04 16:51 UTC, jdrueckert commented on assets/prefabs/items/deerHide.prefab
> +             "Deer hide obtained after killing a deer."
`deerHide` has no information about when it's dropped. So something like "the skin of a deer" would be more suitable I'd say.

2020-07-04 16:51 UTC, jdrueckert commented on assets/prefabs/items/wool.prefab
> +             "Wool obtained after killing a sheep."
see above, maybe rather "soft, thick hair that grows on the bodies of sheep"

2020-07-06 15:54 UTC, jdrueckert approved these changes

2020-07-06 15:54 UTC, merged