Add luring behavior
Terasology/WildAnimals pull request #86
Opened 2021-08-09 22:36 UTC by meetcshah19

Test with [PR](https://github.com/Terasology/Behaviors/pull/79).

How to test:
1. Spawn a sheep using: ```spawnPrefab sheep```
2. Give grass item when in the vicinity of the sheep and have it follow you.

2021-08-19 22:07 UTC, jdrueckert requested changes
I think a unit test for the `modify` method should be relatively easy to do and would help to check how the method behaves properly even given unexpected inputs.

2021-08-19 22:07 UTC, jdrueckert commented on assets/prefabs/animals/sheepBase.prefab
> +    "searchRadius": 8
Tested this out in-game and I think the radius should be a bit bigger, otherwise luring the sheep somewhere specific will be incredibly tedious.

2021-08-19 22:07 UTC, jdrueckert commented on src/main/java/org/terasology/wildAnimals/actions/CheckLuringItemInUseAction.java
> +    public static final String LURING_ITEM = "CoreAssets:Grass";
This is actually the grass (+dirt) block. The grass decoration I would understand (although in JS I think any decoration turns into plant matter. However, using plant matter is only available in JS I think.
Proposal: Use grass / flower decorations as valid luring items and adjust JS to not drop plant matter for flowers at least (might be nice to be able to collect and place flowers for decorative reasons anyway). Or even better, drop plant matter with a high probability and in all other cases the respective item.

2021-08-19 22:07 UTC, jdrueckert commented on src/main/java/org/terasology/wildAnimals/actions/CheckLuringItemInUseAction.java
> +        FindNearbyPlayersComponent component = actor.getComponent(FindNearbyPlayersComponent.class);
can this be `null`?

2021-08-19 22:07 UTC, jdrueckert commented on src/main/java/org/terasology/wildAnimals/actions/CheckLuringItemInUseAction.java
> +        EntityRef player = component.closestCharacter;
can this be `EntityRef.NULL`?

2021-08-19 22:07 UTC, jdrueckert commented on src/main/java/org/terasology/wildAnimals/actions/CheckLuringItemInUseAction.java
> +        EntityRef heldItem = characterHeldItemComponent.selectedItem;
see above

2021-08-20 17:28 UTC, meetcshah19 commented on src/main/java/org/terasology/wildAnimals/actions/CheckLuringItemInUseAction.java
> +        FindNearbyPlayersComponent component = actor.getComponent(FindNearbyPlayersComponent.class);
This component should be definitely not null due to behaviours checking its presence.

2021-08-23 09:08 UTC, meetcshah19 commented on src/main/java/org/terasology/wildAnimals/actions/CheckLuringItemInUseAction.java
> +    public static final String LURING_ITEM = "CoreAssets:Grass";
I think we need to make a proper exhaustive list of items that can be used for luring, given that this is in WildAnimals and will be used by a lot of modules.

2021-08-23 09:09 UTC, meetcshah19 commented on src/main/java/org/terasology/wildAnimals/actions/CheckLuringItemInUseAction.java
> +    public static final String LURING_ITEM = "CoreAssets:Grass";
I am changing item to a lost for now till we decide on the exact list.

2021-08-23 18:56 UTC, keturn commented
I tried this out a bit in game. It seemed like the sheep were following me even if I wasn't holding anything!

2021-08-24 20:55 UTC, jdrueckert commented on src/main/java/org/terasology/wildAnimals/actions/CheckLuringItemInUseAction.java
> +    public static final String LURING_ITEM = "CoreAssets:Grass";
I would go for a few of these: https://github.com/Terasology/CoreAssets/tree/develop/assets/blocks/flora
At least the three tall grass blocks, maybe some of the flowers?
Take care that you need to adjust the drop override that brings in plant matter as suggested above, otherwise it's not possible to get tall grass or flowers in-game.

2021-08-31 18:02 UTC, jdrueckert approved these changes

2021-08-31 18:10 UTC, merged